Map iconValue = {
      "Sunny" : 'assets/images/weather_icon/sunny.png',
      "Sunny night" : 'assets/images/weather_icon/overcast.png',
      "Clear night": 'assets/images/weather_icon/clear_night.png',
      "Clear  night": 'assets/images/weather_icon/clear_night.png',
      "Clear fullmoon": 'assets/images/weather_icon/fullmoon.png',
      "Partly Cloudy" : 'assets/images/weather_icon/partially_cloudy.png',
      "Partly Cloudy " : 'assets/images/weather_icon/partially_cloudy.png',
      "Partly Cloudy night" : 'assets/images/weather_icon/night_partially_cloudy.png',
      "Partly Cloudy  night" : 'assets/images/weather_icon/night_partially_cloudy.png',
      "Cloudy": 'assets/images/weather_icon/cloudy.png',
      "Cloudy night": 'assets/images/weather_icon/night_cloudy.png',
      "Overcast": 'assets/images/weather_icon/overcast.png',
      "Overcast night": 'assets/images/weather_icon/overcast.png',
      "Mist": 'assets/images/weather_icon/overcast.png',
      "Mist night": 'assets/images/weather_icon/overcast.png',
      "Patchy rain nearby": 'assets/images/weather_icon/cloudy_rain.png',
      "Patchy rain nearby night": 'assets/images/weather_icon/night_rain.png',
      "Patchy snow possible": 'assets/images/weather_icon/snow.png',
      "Patchy snow possible night": 'assets/images/weather_icon/night_snow.png',
      "Patchy sleet possible": 'assets/images/weather_icon/snow.png',
      "Patchy sleet possible night": 'assets/images/weather_icon/snow.png',
      "Patchy freezing drizzle possible": 'assets/images/weather_icon/overcast.png',
      "Patchy freezing drizzle possible night": 'assets/images/weather_icon/overcast.png',
      "Thundery outbreaks possible": 'assets/images/weather_icon/thunder.png',
      "Thundery outbreaks possible night": 'assets/images/weather_icon/thunder.png',
      "Blowing snow": 'assets/images/weather_icon/snow.png',
      "Blowing snow night": 'assets/images/weather_icon/snow.png',
      "Blizzard": 'assets/images/weather_icon/snow.png',
      "Blizzard night": 'assets/images/weather_icon/snow.png',
      "Fog": 'assets/images/weather_icon/overcast.png',
      "Fog night": 'assets/images/weather_icon/overcast.png',
      "Freezing fog": 'assets/images/weather_icon/overcast.png',
      "Freezing fog night": 'assets/images/weather_icon/overcast.png',
      "Patchy light drizzle": 'assets/images/weather_icon/cloudy_rain.png',
      "Patchy light drizzle night": 'assets/images/weather_icon/night_cloudy.png',
      "Light drizzle": 'assets/images/weather_icon/cloudy_rain.png',
      "Light drizzle night": 'assets/images/weather_icon/night_rain.png',
      "Freezing drizzle": 'assets/images/weather_icon/overcast.png',
      "Freezing drizzle night": 'assets/images/weather_icon/overcast.png',
      "Heavy freezing drizzle": 'assets/images/weather_icon/overcast.png',
      "Heavy freezing drizzle night": 'assets/images/weather_icon/overcast.png',
      "Patchy light rain": 'assets/images/weather_icon/cludy_rain.png',
      "Patchy light rain night": 'assets/images/weather_icon/night_rain.png',
      "Light rain": 'assets/images/weather_icon/cloudy_rain.png',
      "Light rain night": 'assets/images/weather_icon/night_rain.png',
      "Moderate rain at times": 'assets/images/weather_icon/rain.png',
      "Moderate rain at times night": 'assets/images/weather_icon/night_rain.png',
      "Moderate rain": 'assets/images/weather_icon/rain.png',
      "Moderate rain night": 'assets/images/weather_icon/rain.png',
      "Heavy rain at times": 'assets/images/weather_icon/rain.png',
      "Heavy rain at times night": 'assets/images/weather_icon/rain.png',
      "Heavy rain": 'assets/images/weather_icon/rain.png',
      "Heavy rain rain": 'assets/images/weather_icon/rain.png',
      "Light freezing rain": 'assets/images/weather_icon/rain.png',
      "Light freezing rain night": 'assets/images/weather_icon/rain.png',
      "Moderate or heavy freezing rain": 'assets/images/weather_icon/rain.png',
      "Moderate or heavy freezing rain night": 'assets/images/weather_icon/rain.png',
      "Light sleet": 'assets/images/weather_icon/snow.png',
      "Light sleet night": 'assets/images/weather_icon/night_snow.png',
      "Moderate or heavy sleet": 'assets/images/weather_icon/snow.png',
      "Moderate or heavy sleet night": 'assets/images/weather_icon/snow.png',
      "Patchy light snow": 'assets/images/weather_icon/snow.png',
      "Patchy light snow night": 'assets/images/weather_icon/night_snow.png',
      "Light snow": 'assets/images/weather_icon/snow.png',
      "Light snow night": 'assets/images/weather_icon/night_snow.png',
      "Patchy moderate snow": 'assets/images/weather_icon/snow.png',
      "Patchy moderate snow night": 'assets/images/weather_icon/night_snow.png',
      "Moderate snow": 'assets/images/weather_icon/snow.png',
      "Moderate snow night": 'assets/images/weather_icon/snow.png',
      "Patchy heavy snow": 'assets/images/weather_icon/snow.png',
      "Patchy heavy snow night": 'assets/images/weather_icon/snow.png',
      "Heavy snow": 'assets/images/weather_icon/snow.png',
      "Heavy snow night": 'assets/images/weather_icon/snow.png',
      "Ice pellets": 'assets/images/weather_icon/snow.png',
      "Ice pellets night": 'assets/images/weather_icon/snow.png',
      "Light rain shower": 'assets/images/weather_icon/cloudy_rain.png',
      "Light rain shower night": 'assets/images/weather_icon/night_rain.png',
      "Moderate or heavy rain shower": 'assets/images/weather_icon/rain.png',
      "Moderate or heavy rain shower night": 'assets/images/weather_icon/rain.png',
      "Torrential rain shower": 'assets/images/weather_icon/rain.png',
      "Torrential rain shower night": 'assets/images/weather_icon/rain.png',
      "Light sleet showers": 'assets/images/weather_icon/snow.png',
      "Light sleet showers night": 'assets/images/weather_icon/night_snow.png',
      "Moderate or heavy sleet showers": 'assets/images/weather_icon/snow.png',
      "Moderate or heavy sleet showers night": 'assets/images/weather_icon/night_snow.png',
      "Light snow showers": 'assets/images/weather_icon/snow.png',
      "Light snow showers night": 'assets/images/weather_icon/night_snow.png',
      "Moderate or heavy snow showers": 'assets/images/weather_icon/snow.png',
      "Moderate or heavy snow showers night": 'assets/images/weather_icon/snow.png',
      "Light showers of ice pellets": 'assets/images/weather_icon/snow.png',
      "Light showers of ice pellets night": 'assets/images/weather_icon/snow.png',
      "Moderate or heavy showers of ice pellets": 'assets/images/weather_icon/snow.png',
      "Moderate or heavy showers of ice pellets night": 'assets/images/weather_icon/snow.png',
      "Patchy light rain with thunder": 'assets/images/weather_icon/heavyrain_storm.png',
      "Patchy light rain with thunder night": 'assets/images/weather_icon/heavyrain_storm.png',
      "Moderate or heavy rain with thunder": 'assets/images/weather_icon/heavyrain_storm.png',
      "Moderate or heavy rain with thunder night": 'assets/images/weather_icon/heavyrain_storm.png',
      "Patchy light snow with thunder": 'assets/images/weather_icon/snow.png',
      "Patchy light snow with thunder night": 'assets/images/weather_icon/snow.png',
      "Moderate or heavy snow with thunder": 'assets/images/weather_icon/snow.png',
      "Moderate or heavy snow with thunder night": 'assets/images/weather_icon/snow.png',
};

Map bgValue = {
      "Sunny" : 'assets/images/background_images/sunny.png',
      "Sunny night" : 'assets/images/background_images/overcast.png',
      "Clear night": 'assets/images/background_images/clear_night.png',
      "Clear  night": 'assets/images/background_images/clear_night.png',
      "Clear fullmoon": 'assets/images/background_images/fullmoon.png',
      "Partly Cloudy" : 'assets/images/background_images/partially_cloudy.png',
      "Partly Cloudy night" : 'assets/images/background_images/night_partially_cloudy.png',
      "Partly Cloudy  night" : 'assets/images/background_images/night_partially_cloudy.png',
      "Cloudy": 'assets/images/background_images/cloudy.png',
      "Cloudy night": 'assets/images/background_images/night_cloudy.png',
      "Overcast": 'assets/images/background_images/overcast.png',
      "Overcast night": 'assets/images/background_images/overcast.png',
      "Mist": 'assets/images/background_images/overcast.png',
      "Mist night": 'assets/images/background_images/overcast.png',
      "Patchy rain nearby": 'assets/images/background_images/cloudy_rain.png',
      "Patchy rain nearby night": 'assets/images/background_images/night_rain.png',
      "Patchy snow possible": 'assets/images/background_images/snow.png',
      "Patchy snow possible night": 'assets/images/background_images/night_snow.png',
      "Patchy sleet possible": 'assets/images/background_images/snow.png',
      "Patchy sleet possible night": 'assets/images/background_images/snow.png',
      "Patchy freezing drizzle possible": 'assets/images/background_images/overcast.png',
      "Patchy freezing drizzle possible night": 'assets/images/background_images/overcast.png',
      "Thundery outbreaks possible": 'assets/images/background_images/thunder.png',
      "Thundery outbreaks possible night": 'assets/images/wbackground_images/thunder.png',
      "Blowing snow": 'assets/images/background_images/snow.png',
      "Blowing snow night": 'assets/images/background_images/snow.png',
      "Blizzard": 'assets/images/background_images/snow.png',
      "Blizzard night": 'assets/images/background_images/snow.png',
      "Fog": 'assets/images/background_images/overcast.png',
      "Fog night": 'assets/images/background_images/overcast.png',
      "Freezing fog": 'assets/images/background_images/overcast.png',
      "Freezing fog night": 'assets/images/background_images/overcast.png',
      "Patchy light drizzle": 'assets/images/background_images/cloudy_rain.png',
      "Patchy light drizzle night": 'assets/images/background_images/night_cloudy.png',
      "Light drizzle": 'assets/images/background_images/cloudy_rain.png',
      "Light drizzle night": 'assets/images/background_images/night_rain.png',
      "Freezing drizzle": 'assets/images/background_images/overcast.png',
      "Freezing drizzle night": 'assets/images/background_images/overcast.png',
      "Heavy freezing drizzle": 'assets/images/background_images/overcast.png',
      "Heavy freezing drizzle night": 'assets/images/background_images/overcast.png',
      "Patchy light rain": 'assets/images/background_images/cludy_rain.png',
      "Patchy light rain night": 'assets/images/background_images/night_rain.png',
      "Light rain": 'assets/images/background_images/cloudy_rain.png',
      "Light rain night": 'assets/images/background_images/night_rain.png',
      "Moderate rain at times": 'assets/images/background_images/rain.png',
      "Moderate rain at times night": 'assets/images/background_images/night_rain.png',
      "Moderate rain": 'assets/images/background_images/rain.png',
      "Moderate rain night": 'assets/images/background_images/rain.png',
      "Heavy rain at times": 'assets/images/background_images/rain.png',
      "Heavy rain at times night": 'assets/images/background_images/rain.png',
      "Heavy rain": 'assets/images/background_images/rain.png',
      "Heavy rain rain": 'assets/images/background_images/rain.png',
      "Light freezing rain": 'assets/images/background_images/rain.png',
      "Light freezing rain night": 'assets/images/background_images/rain.png',
      "Moderate or heavy freezing rain": 'assets/images/background_images/rain.png',
      "Moderate or heavy freezing rain night": 'assets/images/background_images/rain.png',
      "Light sleet": 'assets/images/background_images/snow.png',
      "Light sleet night": 'assets/images/background_images/night_snow.png',
      "Moderate or heavy sleet": 'assets/images/background_images/snow.png',
      "Moderate or heavy sleet night": 'assets/images/background_images/snow.png',
      "Patchy light snow": 'assets/images/background_images/snow.png',
      "Patchy light snow night": 'assets/images/background_images/night_snow.png',
      "Light snow": 'assets/images/background_images/snow.png',
      "Light snow night": 'assets/images/background_images/night_snow.png',
      "Patchy moderate snow": 'assets/images/background_images/snow.png',
      "Patchy moderate snow night": 'assets/images/background_images/night_snow.png',
      "Moderate snow": 'assets/images/background_images/snow.png',
      "Moderate snow night": 'assets/images/background_images/snow.png',
      "Patchy heavy snow": 'assets/images/background_images/snow.png',
      "Patchy heavy snow night": 'assets/images/background_images/snow.png',
      "Heavy snow": 'assets/images/background_images/snow.png',
      "Heavy snow night": 'assets/images/background_images/snow.png',
      "Ice pellets": 'assets/images/background_images/snow.png',
      "Ice pellets night": 'assets/images/background_images/snow.png',
      "Light rain shower": 'assets/images/background_images/cloudy_rain.png',
      "Light rain shower night": 'assets/images/background_images/night_rain.png',
      "Moderate or heavy rain shower": 'assets/images/background_images/rain.png',
      "Moderate or heavy rain shower night": 'assets/images/background_images/rain.png',
      "Torrential rain shower": 'assets/images/background_images/rain.png',
      "Torrential rain shower night": 'assets/images/background_images/rain.png',
      "Light sleet showers": 'assets/images/background_images/snow.png',
      "Light sleet showers night": 'assets/images/background_images/night_snow.png',
      "Moderate or heavy sleet showers": 'assets/images/background_images/snow.png',
      "Moderate or heavy sleet showers night": 'assets/images/background_images/night_snow.png',
      "Light snow showers": 'assets/images/background_images/snow.png',
      "Light snow showers night": 'assets/images/background_images/night_snow.png',
      "Moderate or heavy snow showers": 'assets/images/background_images/snow.png',
      "Moderate or heavy snow showers night": 'assets/images/background_imagessnow.png',
      "Light showers of ice pellets": 'assets/images/background_images/snow.png',
      "Light showers of ice pellets night": 'assets/images/background_images/snow.png',
      "Moderate or heavy showers of ice pellets": 'assets/images/background_images/snow.png',
      "Moderate or heavy showers of ice pellets night": 'assets/images/background_images/snow.png',
      "Patchy light rain with thunder": 'assets/imagesbackground_images/heavyrain_storm.png',
      "Patchy light rain with thunder night": 'assets/images/background_images/heavyrain_storm.png',
      "Moderate or heavy rain with thunder": 'assets/images/background_images/heavyrain_storm.png',
      "Moderate or heavy rain with thunder night": 'assets/images/background_images/heavyrain_storm.png',
      "Patchy light snow with thunder": 'assets/images/background_images/snow.png',
      "Patchy light snow with thunder night": 'assets/images/background_images/snow.png',
      "Moderate or heavy snow with thunder": 'assets/images/background_images/snow.png',
      "Moderate or heavy snow with thunder night": 'assets/images/background_images/snow.png',
};
